### ISSUE TITLE
PIL is unable to use the local font

### ISSUE THREAD

**Issue by schemen** [schemen/monsterforge#31]
```
Internal Server Error: /minis/bestiary/2485/print/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/paperminis/views.py", line 305, in bestiary_print
    minis.build_all_and_zip()
  File "/app/paperminis/generate_minis.py", line 99, in build_all_and_zip
    mini = self.build_mini(creature)
  File "/app/paperminis/generate_minis.py", line 251, in build_mini
    unicode_font = ImageFont.truetype("./DejaVuSans.ttf", font_height)
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by wesselsd** [comment]
probably related to the warning contained in the docstring of ImageFont.truetype:

```python3
def truetype(font=None, size=10, index=0, encoding="", layout_engine=None):
  """
  Load a TrueType or OpenType font from a file or file-like object,
  and create a font object.
  This function loads a font object from the given file or file-like
  object, and creates a font object for a font of the given size.
  
  Pillow uses FreeType to open font files. If you are opening many fonts
  simultaneously on Windows, be aware that Windows limits the number of files
  that can be open in C at once to 512. If you approach that limit, an
  ``OSError`` may be thrown, reporting that FreeType "cannot open resource". 
  """
```

To me it seems like this probably looped > 512 times, or something similar:
```python3
while x_margin < 2 or y_margin < 10:
  #print(font_height)
  unicode_font = ImageFont.truetype("DejaVuSans.ttf", font_height)
  font_height = round(font_height - 2, 2)
  textsize = unicode_font.getsize(text)
  im_w, im_h = n_img_pil.size
  x_margin = im_w - textsize[0]
  y_margin = im_h - textsize[1]```
```

**Comment by schemen** [comment]
@alskgj Thanks for the notice! I did find the bug lied somewhere else: The path was wrong. I switched to a slim python image which does not ship all the standard fonts with it which have been used before. 

https://github.com/schemen/monsterforge/commit/e8b6b1185956eecb2661de79963bea09154e5c22

This line of code never worked before but thanks to the bloated image was mostly ignored.
